parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

env:
  browser: true
  es6: true
  jest: true
  worker: true
  serviceworker: true

plugins:
  - babel
  - no-use-extend-native

extends:
  - eslint:recommended

rules:
  no-trailing-spaces: error
  no-multi-spaces: error
  lines-around-directive: error
  linebreak-style:
    - error
    - unix
  strict:
    - error
    - global
  vars-on-top: off
  yoda:
    - error
    - never
  no-use-extend-native/no-use-extend-native:
    - error

  babel/new-cap:
    - error
    - capIsNew: false

  babel/object-curly-spacing:
    - error
    - always